### ISSUE TITLE
PhasedLSTM can accelerate inference too?

### ISSUE THREAD

**Issue by wqingzex** [fferroni/PhasedLSTM-Keras#1]

**Comment by fferroni** [comment]
Hi,

Given that this implementation *adds* calculations associated to the timegate, PhasedLSTM does not accelerate inference per se.

However, given that most of the time (~95%) any given timegate is closed, the inference would greatly benefit from sparse matrix operation libraries like cuSPARSE, thereby accelerating inference. At the moment, there are no such optimisations happening in either backend to my knowledge.
