### ISSUE TITLE
Support for load_model()

### ISSUE THREAD

**Issue by alobbs** [fferroni/PhasedLSTM-Keras#14]
`keras.models.load_model()` does not seem to be supported. Keras throws a `ValueError: Unknown layer: PhasedLSTM` exception when it tries to deserialize the first PLSTM layer.

**Comment by bnaul** [comment]
`load_model` takes a takes a parameter `custom_objects` that should resolve this:
```
custom_objects: Optional dictionary mapping names
                (strings) to custom classes or functions to be
                considered during deserialization.
```
So `load_model(f, {'PhasedLSTM': PhasedLSTM})` should do the trick.

**Comment by alobbs** [comment]
Right. Thanks Brett!
