### ISSUE TITLE
random_example.py: Despite installing, "Unknown layer: PhasedLSTM"

### ISSUE THREAD

**Issue by drscotthawley** [fferroni/PhasedLSTM-Keras#15]
Hi! I'm really interested in trying this out, however, following the instructions to install and then running one of the examples didn't work for me.  I got the same error on both Ubuntu 16.04 running Python 3.6, and with MacOS X High Sierra running Python 3.5:  ValueError: Unknown layer: PhasedLSTM

Any suggestions for getting this to work?  

Below is a log of everything I did, this one for the Mac...

$ pip install phased_lstm_keras
Collecting phased_lstm_keras
  Downloading https://files.pythonhosted.org/packages/73/07/20fe5a59c4e11a42c17763219eb5a3de7c827be7b7d9c1afa5834a4e19b1/phased_lstm_keras-1.0.2-py2.py3-none-any.whl
Requirement already satisfied: matplotlib>=2.0.0 in ./anaconda/envs/py35/lib/python3.5/site-packages (from phased_lstm_keras) (2.2.2)
Requirement already satisfied: numpy>=1.12.1 in ./anaconda/envs/py35/lib/python3.5/site-packages (from phased_lstm_keras) (1.14.0)
Requirement already satisfied: keras>=2.0.2 in ./anaconda/envs/py35/lib/python3.5/site-packages (from phased_lstm_keras) (2.1.3)
Requirement already satisfied: cycler>=0.10 in ./anaconda/envs/py35/lib/python3.5/site-packages (from matplotlib>=2.0.0->phased_lstm_keras) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./anaconda/envs/py35/lib/python3.5/site-packages (from matplotlib>=2.0.0->phased_lstm_keras) (2.1.10)
Requirement already satisfied: python-dateutil>=2.1 in ./anaconda/envs/py35/lib/python3.5/site-packages (from matplotlib>=2.0.0->phased_lstm_keras) (2.6.1)
Requirement already satisfied: pytz in ./anaconda/envs/py35/lib/python3.5/site-packages (from matplotlib>=2.0.0->phased_lstm_keras) (2017.3)
Requirement already satisfied: six>=1.10 in ./anaconda/envs/py35/lib/python3.5/site-packages (from matplotlib>=2.0.0->phased_lstm_keras) (1.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda/envs/py35/lib/python3.5/site-packages (from matplotlib>=2.0.0->phased_lstm_keras) (1.0.1)
Requirement already satisfied: scipy>=0.14 in ./anaconda/envs/py35/lib/python3.5/site-packages (from keras>=2.0.2->phased_lstm_keras) (1.0.0)
Requirement already satisfied: pyyaml in ./anaconda/envs/py35/lib/python3.5/site-packages (from keras>=2.0.2->phased_lstm_keras) (3.12)
Requirement already satisfied: setuptools in ./anaconda/envs/py35/lib/python3.5/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.0->phased_lstm_keras) (39.0.1)
Installing collected packages: phased-lstm-keras
Successfully installed phased-lstm-keras-1.0.2

$ git clone https://github.com/fferroni/PhasedLSTM-Keras.git
Cloning into 'PhasedLSTM-Keras'...
remote: Counting objects: 101, done.
remote: Total 101 (delta 0), reused 0 (delta 0), pack-reused 101
Receiving objects: 100% (101/101), 363.37 KiB | 2.04 MiB/s, done.
Resolving deltas: 100% (40/40), done.

$ cd PhasedLSTM-Keras/examples/
$ python random_example.py 
/Users/shawley/anaconda/envs/py35/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/Users/shawley/anaconda/envs/py35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
2018-04-22 12:51:22.827292: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
lstm_1 (LSTM)                (None, 10)                520       
=================================================================
Total params: 520
Trainable params: 520
Non-trainable params: 0
_________________________________________________________________
Traceback (most recent call last):
  File "random_example.py", line 31, in <module>
    main()
  File "random_example.py", line 23, in main
    model_plstm = load_model('model_plstm.h5')
  File "/Users/shawley/anaconda/envs/py35/lib/python3.5/site-packages/keras/models.py", line 243, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/Users/shawley/anaconda/envs/py35/lib/python3.5/site-packages/keras/models.py", line 317, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/Users/shawley/anaconda/envs/py35/lib/python3.5/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/Users/shawley/anaconda/envs/py35/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 143, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/shawley/anaconda/envs/py35/lib/python3.5/site-packages/keras/models.py", line 1352, in from_config
    layer = layer_module.deserialize(conf, custom_objects=custom_objects)
  File "/Users/shawley/anaconda/envs/py35/lib/python3.5/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/Users/shawley/anaconda/envs/py35/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 137, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: PhasedLSTM

$ which python
/Users/shawley/anaconda/envs/py35/bin/python
(py35) Scotts-MacBook-Pro-3:examples shawley$ python --version
Python 3.5.3

**Comment by WillieMaddox** [comment]
Same problem here on Ubuntu 16.04 Python 3.6.3

**Comment by nicolefinnie** [comment]
The problem is you need to define `custom_objects` for your custom layers `PhasedLSTM` when you load the model.

Usually the following line should work out of box since the custom objects have been defined in `PhasedLSTM.py`

```
model_plstm = load_model('model_plstm.h5', custom_objects={"PhasedLSTM", PhasedLSTM} )
```

However, it doesn't. And I just downgraded to Keras 2.1.5 to bypass the first Keras/tensorflow bug and changed `random_example.py` as follows, this should work. 

```
from keras.utils import CustomObjectScope

with CustomObjectScope({'PhasedLSTM': PhasedLSTM}):
        model_plstm = load_model('model_plstm.h5')
```

**Comment by drscotthawley** [comment]
@nicolefinnie answered this correctly. thanks.
