### ISSUE TITLE
License

### ISSUE THREAD

**Issue by adr-arroyo** [fferroni/PhasedLSTM-Keras#18]
Dear Francesco,
I apologize for writing to you here, as I could not find any other contact method.

We would like to use your implementation of PhasedLSTM for Keras in our projects. However, we have seen that your license for using it is GNU General Public License v3.0, which obligates that our project also is released under it. Despite planning to release it as open source software, we are still debating on which license is going to be used but we do not want it to be GPL, and yours limits us to just GPL3.

Has it happened this before to you? Is it possible for you to modify the license of your library?

Sorry for any inconvenience and thank you

**Comment by fferroni** [comment]
Done. If you make any functional improvements please commit them in the spirit of open source :)

**Comment by adr-arroyo** [comment]
Dear Francesco, 
I very much appreciate this gesture. Any improvement & experiment/study will be committed/updated.

Thanks, Adrian
