### ISSUE TITLE
Add package to pypi

### ISSUE THREAD

**Issue by jonnyniv** [fferroni/PhasedLSTM-Keras#5]
I was unable to find the package on pypi, which would allow a user to install it with pip.
The [twine](https://pypi.python.org/pypi/twine) package is a good helper to allow this to go smoothly.

**Comment by fferroni** [comment]
@albertaparicio made a commit sometime ago to make it pip installable. Might want to ask him?

**Comment by albertaparicio** [comment]
@jonnyniv Some time ago I prepared this repository so that it can be installed locally with pip, but I did not upload it to PyPi.

If you want to install it, you can clone the repo on your machine and use `pip install REPO_DIR`.

@fferroni you could consider uploading the library onto PyPi, too.

**Comment by jonnyniv** [comment]
@albertaparicio Thanks for the update. Installing directly from the repo worked fine. It would be nice to have the package on PyPi, but this is good enough for now.

**Comment by fferroni** [comment]
Hello,

I updated the repo for the latest Keras 2.0 API (works for me on Tensorflow 1.0 and Theano 0.9), and you can now pip install it using:
`pip install phased_lstm_keras`
